FROM python:3.11-slim
WORKDIR /app

COPY requirements-ui.txt .
RUN pip install --no-cache-dir -r requirements-ui.txt

COPY app/ ./app/
COPY .streamlit/ .streamlit/

EXPOSE 8501
CMD ["streamlit", "run", "app/ui/main.py", "--server.port=8501"]